### ISSUE TITLE
Land use table inherits wrong floors data

### ISSUE THREAD

**Issue by jorgegil** [OpenDigitalWorks/UrbanDataInputTool#13]
When converting existing layer to land use table, a second column (not relevant) was used to populate the floors column.
The tool cannot inherit data implicitly without asking as the existing attributes are totally unpredictable. The most important is to keep the ID column, the user can later join and transfer attributes if necessary.

**Comment by Morri1234** [comment]
Fixed by adding Select ID column while creating new file. Now only the ID column of the building layer is retained over.
