### ISSUE TITLE
Creating LU as shape from buildings overwrites buildings layer

### ISSUE THREAD

**Issue by jorgegil** [OpenDigitalWorks/UrbanDataInputTool#16]
When creating a new land use layer in shape file format, based on an existing buildings layer, that layer gets transformed as well and removed from the legend (so the user does not even realise the original data was changed).
The same does not happen when creating a new land use layer as a memory layer.

**Comment by Morri1234** [comment]
Fixed by creating a memory layer and copying the features and ID attribute to the new layer.
