### ISSUE TITLE
Updating attributes in table does not refresh 

### ISSUE THREAD

**Issue by Anafi** [OpenDigitalWorks/UrbanDataInputTool#4]

**Comment by gregmaya** [comment]
This happens only when the user changes an attribute of the table created attribute with a random value that is not included in the predefined categories

**Comment by jorgegil** [comment]
I don't think editing attributes should be possible, as this breaks the purpose of the tool: to have a standard and consistent method for entering urban data.
To make if according to different standards, we should implement a settings feature where users can customise the categories. Or have it in text files that are easy to edit.
